// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PCcIn5boVRipHb0q-JcBq8EF9LYu3eg',
    appId: '1:1009485790036:web:89cd73db90a3fe1b28e6c1',
    messagingSenderId: '1009485790036',
    projectId: 'japanese-learn-1fa7d',
    authDomain: 'japanese-learn-1fa7d.firebaseapp.com',
    storageBucket: 'japanese-learn-1fa7d.firebasestorage.app',
    measurementId: 'G-5GG8DR68SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2u13hZ0TjuHeon3gZ2Sf4BSthjyxLmEY',
    appId: '1:1009485790036:android:f4b8c2b9c45e849a28e6c1',
    messagingSenderId: '1009485790036',
    projectId: 'japanese-learn-1fa7d',
    storageBucket: 'japanese-learn-1fa7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBstD10wA_HA0HgS_FVT9IiRu0GABSAXag',
    appId: '1:1009485790036:ios:53cbb8be17b2d9c128e6c1',
    messagingSenderId: '1009485790036',
    projectId: 'japanese-learn-1fa7d',
    storageBucket: 'japanese-learn-1fa7d.firebasestorage.app',
    androidClientId: '1009485790036-2v2dseutehumgtukj6otqqelpeug5ibk.apps.googleusercontent.com',
    iosClientId: '1009485790036-purube8oigcc8nml2gb5qlpmlgahc510.apps.googleusercontent.com',
    iosBundleId: 'com.example.nihongo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBstD10wA_HA0HgS_FVT9IiRu0GABSAXag',
    appId: '1:1009485790036:ios:53cbb8be17b2d9c128e6c1',
    messagingSenderId: '1009485790036',
    projectId: 'japanese-learn-1fa7d',
    storageBucket: 'japanese-learn-1fa7d.firebasestorage.app',
    androidClientId: '1009485790036-2v2dseutehumgtukj6otqqelpeug5ibk.apps.googleusercontent.com',
    iosClientId: '1009485790036-purube8oigcc8nml2gb5qlpmlgahc510.apps.googleusercontent.com',
    iosBundleId: 'com.example.nihongo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6PCcIn5boVRipHb0q-JcBq8EF9LYu3eg',
    appId: '1:1009485790036:web:5eef2477d5d67bab28e6c1',
    messagingSenderId: '1009485790036',
    projectId: 'japanese-learn-1fa7d',
    authDomain: 'japanese-learn-1fa7d.firebaseapp.com',
    storageBucket: 'japanese-learn-1fa7d.firebasestorage.app',
    measurementId: 'G-TGM6EQWVJH',
  );
}
